# Generated by Django 5.0.2 on 2024-02-27 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('CLO_name', models.CharField(max_length=150)),
                ('CLO_id', models.IntegerField(primary_key=True, serialize=False)),
                ('CLO_domain', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=150, unique=True)),
                ('course_name', models.CharField(max_length=15)),
                ('credit_hours', models.IntegerField()),
                ('course_offer_level', models.IntegerField()),
                ('pre_requisites', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=250, verbose_name='Department Id')),
                ('depat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Department Id')),
                ('dept_major', models.CharField(max_length=250)),
                ('dept_faculty_count', models.IntegerField(verbose_name='department faculty count')),
                ('dept_student_count', models.IntegerField(verbose_name='department student count')),
                ('dept_hod', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('semester_choice', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
            ],
        ),
    ]
