# Generated by Django 5.0.2 on 2024-02-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depat_id',
            new_name='dept_id',
        ),
        migrations.AddField(
            model_name='clo',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abet.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abet.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abet.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
