# Generated by Django 5.0.2 on 2024-02-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 16, 41, 26, 967212, tzinfo=datetime.timezone.utc)),
        ),
    ]
