# Generated by Django 5.0.2 on 2024-02-26 22:16

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_newdepartment_alter_newuser_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDepartment',
            fields=[
                ('dept_name', models.CharField(max_length=250, verbose_name='Department Id')),
                ('depat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Department Id')),
                ('dept_major', models.CharField(max_length=250)),
                ('dept_faculty_count', models.IntegerField(verbose_name='department faculty count')),
                ('dept_student_count', models.IntegerField(verbose_name='department student count')),
                ('dept_hod', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 22, 16, 38, 792984, tzinfo=datetime.timezone.utc)),
        ),
    ]
