# Generated by Django 5.0.2 on 2024-02-26 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_newdepartment_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 22, 53, 24, 657889, tzinfo=datetime.timezone.utc)),
        ),
    ]
