# Generated by Django 5.0.2 on 2024-02-27 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 14, 44, 139781, tzinfo=datetime.timezone.utc)),
        ),
    ]
