# Generated by Django 5.0.2 on 2024-02-27 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 52, 51, 320172, tzinfo=datetime.timezone.utc)),
        ),
    ]
